# === DATABASE CONFIG === #
spring.datasource.url=jdbc:postgresql://localhost:5433/todo
spring.datasource.username=todo
spring.datasource.password=todo

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# === DATE / TIME FORMAT === #

spring.mvc.format.date-time=yyyy-MM-dd'T'HH:mm::ss
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.time=HH:mm:ss